#!/usr/bin/env python3
"""check_release_commands.py -- can a reader actually RUN what each release row cites?

Exit 0 PASS / 1 FAIL / 2 CANNOT DETERMINE.

WHY
  MISSION.md's definition of done: "every item generated by a tool on this machine and
  graded PASS, NEVER ASSERTED."  Measured 2026-09-05: the READY / PARTIAL badge in
  out/release/README.md is a hand-written `status` field in spec/release-pack.json.
  gen_release_pack.py only formats it.  Nothing compares a row's badge to what its own
  `command` returns.

  L9 established that all 51 evidence citations RESOLVE -- the files are on disk.  This
  is the next question and a different one: **can the command be run at all?**  A row
  whose command still contains `<board>` cannot be executed by the factory, by a
  reviewer, or by us.  Its badge is then an assertion no matter how good the evidence is.

WHAT IT DOES *NOT* DO, and this is deliberate on an 8 GB machine that has panicked twice
  this week: it DOES NOT EXECUTE ANYTHING by default.  Several rows cite a ten-pass
  autorouter, an EM solve and a firmware build.  Classification is static.  `--run`
  exists and executes ONLY rows classed RUNNABLE-LIGHT, with a timeout, and it refuses
  anything needing the network.

CLASSES
  RUNNABLE-LIGHT   no placeholder, every named tool on disk, no network, not on the
                   heavy list -- a reader can run it now

  WHAT A PLACEHOLDER ROW IS AND IS NOT.  `<bom.json>` is a documentation TEMPLATE, and
  L9 was right that a template is not a citation.  This tool does NOT claim such a row
  is unevidenced -- L9 measured that all 51 evidence citations resolve, 30 files, 8
  directories, 13 commits.  It claims something narrower and still worth fixing: the
  pack lets a reader confirm the evidence EXISTS and not that it is CORRECT, because
  there is no line they can run.  For a pack whose mission says "generated by a tool on
  this machine and GRADED PASS, never asserted", the reproduction line IS the grade.
  A file on disk is not a grade.
  RUNNABLE-HEAVY   as above but names a solver / router / build, so it is real but not
                   free
  NEEDS-NETWORK    carries --live; a reader offline cannot reproduce the badge
  PLACEHOLDER      contains <...>; NOBODY can run it as written
  MISSING-TOOL     names a path that is not on disk
  NONE             no command at all

CONTROLS, all run every time
  C1 a synthetic row citing a real light tool must classify RUNNABLE-LIGHT
  C2 a synthetic row containing <board> must classify PLACEHOLDER
  C3 a synthetic row naming a tool that does not exist must classify MISSING-TOOL
  If any control misclassifies, no scan is published.
"""
import argparse, json, os, re, shlex, subprocess, sys

PASS, FAIL, CANNOT = 0, 1, 2
HERE = os.path.dirname(os.path.abspath(__file__))
HALO = os.path.dirname(HERE)
WORKSHOP = os.path.dirname(os.path.dirname(HALO))

HEAVY = ("route_board", "openems", "rf antenna", "fwsim build", "cad ", "panel",
         "--passes", "spice run")
PLACEHOLDER = re.compile(r"<[^>]+>")


def say(*a):
    print(*a, file=sys.stderr)


def tools_in(cmd):
    """Every token that looks like a path to something executable."""
    out = []
    for chunk in re.split(r"[;&|]|\bthen\b", cmd):
        toks = chunk.strip().split()
        if not toks:
            continue
        i = 0
        if toks[0] in ("python3", "python", "sh", "bash"):
            i = 1
        if i < len(toks):
            t = toks[i]
            if "/" in t or t.endswith((".py", ".sh")):
                out.append(t)
    return out


def resolve(t):
    for root in (HALO, WORKSHOP):
        p = os.path.join(root, t)
        if os.path.exists(p):
            return p
    return None


def classify(cmd):
    if not cmd or cmd.strip() in ("", "—", "-"):
        return "NONE", [], "no command is cited at all"
    if PLACEHOLDER.search(cmd):
        return "PLACEHOLDER", [], ("contains " +
                                   ", ".join(sorted(set(PLACEHOLDER.findall(cmd)))) +
                                   " -- a TEMPLATE, not a reproduction line")
    ts = tools_in(cmd)
    missing = [t for t in ts if resolve(t) is None]
    if missing:
        return "MISSING-TOOL", ts, f"not on disk: {missing}"
    if "--live" in cmd:
        return "NEEDS-NETWORK", ts, "carries --live; an offline reader cannot reproduce it"
    if any(h in cmd for h in HEAVY):
        return "RUNNABLE-HEAVY", ts, "real, but it runs a solver, router or build"
    return "RUNNABLE-LIGHT", ts, "a reader can run this now"


def suggest(ph, cmd):
    """Candidate concrete arguments found ON DISK for a placeholder. SUGGESTIONS ONLY --
    the lane that owns the row confirms which one it actually ran, because guessing
    which bom.json was used would replace an honest gap with a wrong answer."""
    import glob
    pat = {
        "<board>": "electronics/**/out/*.kicad_pcb",
        "<board>.kicad_pcb": "electronics/**/out/*.kicad_pcb",
        "<name>.kicad_sch": "electronics/**/*.kicad_sch",
        "<name>": "electronics/**/*.kicad_sch",
        "<bom.json>": "**/bom.json",
        "<spec.json>": "**/antenna*.json",
        "<example>": None,
    }.get(ph)
    if not pat:
        return []
    hits = sorted(glob.glob(os.path.join(HALO, pat), recursive=True))[:4]
    return [os.path.relpath(h, HALO) for h in hits]


def selftest():
    ok = True
    real = "tools/gen_release_pack.py" if resolve("tools/gen_release_pack.py") else None
    cases = [
        (f"python3 {real}", "RUNNABLE-LIGHT", "C1"),
        ("ce-pcb/bin/sch erc <name>.kicad_sch", "PLACEHOLDER", "C2"),
        ("python3 tools/no_such_tool_xyz.py", "MISSING-TOOL", "C3"),
    ]
    for cmd, want, name in cases:
        if cmd.endswith("None"):
            say(f"{name} CANNOT DETERMINE: no real light tool to build the case from")
            return False
        got, _, why = classify(cmd)
        say(f"{name}: {got:15s} (want {want})   {why}")
        if got != want:
            say(f"{name} FIRED: misclassified.")
            ok = False
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default=os.path.join(HALO, "spec", "release-pack.json"))
    ap.add_argument("--run", action="store_true",
                    help="execute ONLY the RUNNABLE-LIGHT rows and compare the exit "
                         "code to the declared status")
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    say("CONTROLS FIRST")
    if not selftest():
        say("FAIL: the classifier's own controls did not pass. No scan is published.")
        sys.exit(FAIL)
    say("")

    d = json.load(open(a.spec))
    rows, counts = [], {}
    for art in d["artifacts"]:
        cls, ts, why = classify(art.get("command", ""))
        counts[cls] = counts.get(cls, 0) + 1
        rows.append(dict(n=art["n"], name=art["name"], declared_status=art["status"],
                         command=art.get("command", ""), klass=cls, tools=ts, why=why))
    say(f"{len(rows)} rows in {os.path.relpath(a.spec, HALO)}")
    for r in rows:
        say(f"  {r['n']:2d} {r['declared_status']:8s} {r['klass']:15s} {r['why']}")
    say("")
    say("  " + " · ".join(f"{v} {k}" for k, v in sorted(counts.items())))

    runnable = counts.get("RUNNABLE-LIGHT", 0)
    unverifiable = (counts.get("PLACEHOLDER", 0) + counts.get("NONE", 0)
                    + counts.get("MISSING-TOOL", 0))
    say("")
    say(f"VERIFIABLE BY FOLLOWING THE ROW'S OWN COMMAND: {runnable} of {len(rows)}")
    say(f"NOT RUNNABLE AS WRITTEN BY ANYONE: {unverifiable} of {len(rows)} "
        f"(placeholder, missing tool, or no command)")
    ready_unverifiable = [r for r in rows if r["declared_status"] == "READY"
                          and r["klass"] in ("PLACEHOLDER", "NONE", "MISSING-TOOL")]
    if ready_unverifiable:
        say("")
        say("ROWS BADGED **READY** THAT CARRY NO REPRODUCTION LINE -- their evidence "
            "resolves (L9: 51/51) but nobody else can re-derive it:")
        for r in ready_unverifiable:
            say(f"  {r['n']:2d} {r['name']}  --  {r['why']}")
            for ph in sorted(set(PLACEHOLDER.findall(r["command"]))):
                sg = suggest(ph, r["command"])
                r.setdefault("suggestions", {})[ph] = sg
                say(f"        {ph} -> " + (", ".join(sg) if sg else
                                           "no candidate found on disk; the owning lane "
                                           "must say what it ran"))

    ran = []
    if a.run:
        say("")
        for r in rows:
            if r["klass"] != "RUNNABLE-LIGHT":
                continue
            # a row may chain several commands with ';'. Run each; the row passes only
            # if every part does. shlex.split on the whole string would hand ';' to the
            # first tool as an argument and call the result a run.
            parts = [x.strip() for x in r["command"].split(";") if x.strip()]
            code, note = 0, ""
            for part in parts:
                try:
                    p = subprocess.run(shlex.split(part), cwd=HALO, capture_output=True,
                                       text=True, timeout=a.timeout)
                    if p.returncode != 0:
                        code = p.returncode
                        note = f"[{part[:40]}] {(p.stderr or p.stdout).strip()[-160:]}"
                        break
                except Exception as e:
                    code, note = None, f"[{part[:40]}] {str(e)[:100]}"
                    break
            r["parts_run"] = len(parts)
            agree = (code == 0) if r["declared_status"] == "READY" else None
            r["exit_code"] = code
            r["run_note"] = note
            r["status_matches_exit"] = agree
            ran.append(r)
            say(f"  ran row {r['n']}: exit {code}  declared {r['declared_status']}  "
                f"{'AGREES' if agree else ('DISAGREES' if agree is False else 'n/a')}"
                f"{'  ' + note if note else ''}")

    if a.out:
        json.dump(dict(tool="check_release_commands.py",
                       what_this_is=("does each release row cite a command a reader can "
                                     "actually run? It does NOT execute by default."),
                       spec=os.path.relpath(a.spec, HALO), counts=counts,
                       verifiable_light=runnable,
                       not_runnable_as_written=unverifiable,
                       ready_but_unrunnable=[r["n"] for r in ready_unverifiable],
                       ran=[r["n"] for r in ran], rows=rows),
                  open(a.out, "w"), indent=2)
        say(f"wrote {a.out}")

    if unverifiable > len(rows) / 2:
        say("")
        say("CANNOT DETERMINE: more than half the pack cites a command that cannot be "
            "run as written, so the pack's badges cannot be checked against its own "
            "instructions. That is a statement about the SPEC, not about the artifacts.")
        sys.exit(CANNOT)
    if ready_unverifiable:
        say("")
        say("FAIL: a row badged READY carries no line a reader can run to re-derive it. "
            "Its evidence resolves; its GRADE does not reproduce. MISSION.md requires "
            "every item generated by a tool on this machine and GRADED PASS.")
        sys.exit(FAIL)
    say("PASS")
    sys.exit(PASS)


if __name__ == "__main__":
    main()
