#!/usr/bin/env python3
"""Generate out/release/ from spec/release-pack.json. Nothing here is hand-typed HTML."""
import json, pathlib, datetime, html, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "spec" / "release-pack.json").read_text())
OUT = ROOT / "out" / "release"
OUT.mkdir(parents=True, exist_ok=True)
E = html.escape

def rev():
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                              capture_output=True, text=True).stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def _deliverables_present(art):
    """Which of an artifact's named deliverables are actually on disk.

    MEASURED 2026-09-05, and this is why it exists: every status in this pack was
    a LITERAL typed into the data file. The generator's only subprocess call was
    `git rev-parse`. Ten of eleven artifacts record a proving COMMAND and NONE of
    them was ever run. The statuses were right by MAINTENANCE rather than by
    MEASUREMENT — and one had drifted to READY with no deliverable at all: item 5
    cites a panel "proven on the Ø31.87 mm round board", which is the SHELL
    diameter, while this board is 25.6138 x 26.0000 mm and `find out/release
    -iname '*panel*'` returns nothing.

    This is the document a factory acts on, and MISSION.md's own words are
    "generated by a tool on this machine and graded PASS, never asserted".

    Full derivation — running each recorded command — is the right end state and
    is not this. This is the cheap half that catches the failure that actually
    happened: A NAMED DELIVERABLE THAT IS NOT ON DISK CANNOT BE READY.
    """
    import glob as _glob
    found, missing = [], []
    for pat in art.get("deliverables") or []:
        hits = _glob.glob(str(ROOT / pat))
        (found if hits else missing).append(pat)
    return found, missing


STATUS_ORDER = {"READY": 0, "PARTIAL": 1, "NOT STARTED": 2}
CSS = """
:root{--ink:#16181d;--dim:#5c6370;--line:#dfe3e8;--bg:#fff;--ready:#0a7d33;--partial:#a86500;--not:#a11}
@media(prefers-color-scheme:dark){:root{--ink:#e8eaed;--dim:#9aa2ad;--line:#2c313a;--bg:#14161a;--ready:#4ec26f;--partial:#e0a233;--not:#f0736a}}
*{box-sizing:border-box}
body{margin:0;padding:2.5rem 1.5rem 6rem;background:var(--bg);color:var(--ink);
 font:16px/1.65 -apple-system,"Helvetica Neue","PingFang SC","Microsoft YaHei",sans-serif}
main{max-width:64rem;margin:0 auto}
h1{font-size:2rem;margin:0 0 .2rem;letter-spacing:-.02em}
h2{font-size:1.25rem;margin:3rem 0 .75rem;padding-bottom:.4rem;border-bottom:1px solid var(--line)}
h3{font-size:1rem;margin:1.75rem 0 .4rem}
.sub{color:var(--dim);margin:0 0 1.5rem}
table{border-collapse:collapse;width:100%;margin:1rem 0;font-size:.92rem}
th,td{text-align:left;vertical-align:top;padding:.55rem .7rem;border-bottom:1px solid var(--line)}
th{font-weight:600;color:var(--dim);font-size:.8rem;text-transform:uppercase;letter-spacing:.05em}
td.n{width:2.5rem;color:var(--dim);font-variant-numeric:tabular-nums}
.badge{display:inline-block;font-size:.72rem;font-weight:700;letter-spacing:.06em;padding:.15rem .45rem;
 border-radius:3px;border:1px solid currentColor;white-space:nowrap}
.READY{color:var(--ready)} .PARTIAL{color:var(--partial)} .NOT{color:var(--not)}
code,.mono{font:.85em ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--dim);word-break:break-all}
blockquote{margin:1rem 0;padding:.8rem 1.1rem;border-left:3px solid var(--line);color:var(--ink);background:rgba(127,127,127,.06)}
.zh{color:var(--dim);font-size:.9em}
.meta{color:var(--dim);font-size:.82rem;margin-top:3rem;padding-top:1rem;border-top:1px solid var(--line)}
ul{padding-left:1.2rem} li{margin:.3rem 0}
.owner{font-size:.75rem;font-weight:600;color:var(--dim);letter-spacing:.04em}
"""

def badge(s):
    return f'<span class="badge {"NOT" if s=="NOT STARTED" else E(s)}">{E(s)}</span>'

p = []
a = p.append
a(f'<!doctype html><html lang="en"><meta charset="utf-8">')
a(f'<meta name="viewport" content="width=device-width,initial-scale=1">')
a(f'<title>{E(DATA["title"])} — {E(DATA["subtitle"])}</title><style>{CSS}</style><main>')
a(f'<h1>{E(DATA["title"])}</h1>')
a(f'<p class="sub">{E(DATA["subtitle"])} · generated {datetime.date.today().isoformat()} · commit <span class="mono">{rev()}</span></p>')
a(f'<p>{E(DATA["summary_en"])}</p>')
a(f'<p class="zh">{E(DATA["summary_zh"])}</p>')
a(f'<blockquote>{E(DATA["leif_verbatim"])}</blockquote>')

# Demote before counting. A status is not a claim anyone gets to type.
for x in DATA["artifacts"]:
    _found, _missing = _deliverables_present(x)
    x["_deliverables_found"], x["_deliverables_missing"] = _found, _missing
    if _missing and x["status"] == "READY":
        x["status"] = "PARTIAL"
        x["reason"] = ("DEMOTED FROM READY BY THE GENERATOR: named deliverable(s) "
                       + ", ".join(_missing) + " are not on disk. " + x["reason"])

counts = {}
for x in DATA["artifacts"]:
    counts[x["status"]] = counts.get(x["status"], 0) + 1
tally = " · ".join(f'{counts.get(k,0)} {k.lower()}' for k in ["READY","PARTIAL","NOT STARTED"])
a(f'<h2>1 · The release pack as it stands — {E(tally)}</h2>')
a('<p>Eleven artifacts define a finished product. Each row states what exists today, the evidence behind that verdict, and the command that produces it. Nothing is listed as ready on the strength of a plan.</p>')
a('<table><tr><th>#</th><th>Artifact</th><th>Status</th><th>Where it stands</th></tr>')
for x in sorted(DATA["artifacts"], key=lambda r: (STATUS_ORDER[r["status"]], r["n"])):
    a(f'<tr><td class="n">{x["n"]}</td><td><b>{E(x["name"])}</b><br><span class="zh">{E(x["name_zh"])}</span></td>'
      f'<td>{badge(x["status"])}</td><td>{E(x["reason"])}'
      f'<br><span class="mono">evidence: {E(x["evidence"])}</span>'
      f'<br><span class="mono">command: {E(x["command"])}</span>'
      f'<br><span class="mono">deliverables on disk: {len(x.get("_deliverables_found") or [])}'
      f'{" — MISSING: " + E(", ".join(x["_deliverables_missing"])) if x.get("_deliverables_missing") else ""}'
      f'</span></td></tr>')
a('</table>')

a('<h2>2 · The work breakdown — ten parcels for ten engineers</h2>')
a('<p>Each parcel is a deliverable, the test that accepts it, what it needs first, and what it unblocks. Parcels marked in flight already have an agent working on them here — coordinate rather than duplicate.</p>')
for x in DATA["parcels"]:
    a(f'<h3>{x["n"]} · {E(x["title"])} <span class="zh">{E(x.get("title_zh",""))}</span> — <span class="owner">{E(x["owner"])}</span></h3>')
    a('<table>')
    for label, key in [("Deliverable","deliverable"),("Accepted when","acceptance"),("Needs first","depends"),("Unblocks","unblocks")]:
        a(f'<tr><th style="width:9rem">{label}</th><td>{E(x[key])}</td></tr>')
    a('</table>')

a('<h2>3 · What we need from you</h2>')
a('<p>These cannot be settled on a computer. They are the reason a real factory changes this project more than any amount of further research would.</p>')
a('<table><tr><th>Question</th><th>Why it matters</th></tr>')
for q in DATA["questions"]:
    a(f'<tr><td><b>{E(q["q"])}</b><br><span class="zh">{E(q["zh"])}</span></td><td>{E(q["why"])}</td></tr>')
a('</table>')

a('<h2>4 · Licence and compliance — read before tooling</h2>')
a('<table><tr><th>Rule</th><th>What it means for manufacturing</th></tr>')
for c in DATA["compliance"]:
    a(f'<tr><td><b>{E(c["rule"])}</b><br><span class="zh">{E(c["zh"])}</span></td><td>{E(c["detail"])}</td></tr>')
a('</table>')

a('<h2>5 · Open risks, stated plainly</h2><ul>')
for r in DATA["risks"]:
    a(f'<li><b>{E(r["r"])}</b> — {E(r["d"])}</li>')
a('</ul>')

a(f'<p class="meta">{E(DATA["generated_note"])} Regenerate with '
  f'<code>python3 tools/gen_release_pack.py</code>. Audience: {E(DATA["audience"])}</p>')
a('</main></html>')

(OUT / "INDEX.html").write_text("\n".join(p), encoding="utf-8")

lines = [f"# {DATA['title']} — {DATA['subtitle']}", "",
         f"Generated {datetime.date.today().isoformat()} from `spec/release-pack.json` by `tools/gen_release_pack.py`.",
         "", "| # | artifact | status |", "|---|---|---|"]
for x in DATA["artifacts"]:
    lines.append(f"| {x['n']} | {x['name']} | **{x['status']}** |")
lines += ["", "See `INDEX.html` for the full pack: the work breakdown, what we need from the factory,",
          "the compliance rules, and the open risks."]
(OUT / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT/'INDEX.html'} ({(OUT/'INDEX.html').stat().st_size} bytes) and README.md")
print(tally)
